spring:
  application:
    name: config-client
  cloud:
    config:
      label: master                   #\u5BF9\u5E94git\u7684\u5206\u652F\u3002\u5982\u679C\u914D\u7F6E\u4E2D\u5FC3\u4F7F\u7528\u7684\u662F\u672C\u5730\u5B58\u50A8\uFF0C\u5219\u8BE5\u53C2\u6570\u65E0\u7528
      profile: pro                    #\u5BF9\u5E94{profile}\u90E8\u5206
      #uri: http://localhost:8888/    #\u914D\u7F6E\u4E2D\u5FC3\u7684\u5177\u4F53\u5730\u5740
      name: springcloud-config        #\u5BF9\u5E94{application}\u90E8\u5206
      discovery:
        service-id: config-server     #\u6307\u5B9A\u914D\u7F6E\u4E2D\u5FC3\u7684service-id\uFF0C\u4FBF\u4E8E\u6269\u5C55\u4E3A\u9AD8\u53EF\u7528\u914D\u7F6E\u96C6\u7FA4
      enabled: true                   #\u5F00\u542FConfig\u670D\u52A1\u53D1\u73B0\u652F\u6301
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: 192.168.1.134
    port: 5672
    username: admin
    password: admin

server:
  port: 8082
eureka:
  client:
    service-url:
      #\u8BBE\u7F6E\u4E0EEureka Server\u4EA4\u4E92\u7684\u5730\u5740\uFF0C\u67E5\u8BE2\u670D\u52A1\u548C\u6CE8\u518C\u670D\u52A1\u90FD\u9700\u8981\u4F9D\u8D56\u8FD9\u4E2A\u5730\u5740\u3002\u9ED8\u8BA4\u662Fhttp://localhost:8761/eureka \uFF1B\u591A\u4E2A\u5730\u5740\u53EF\u4F7F\u7528 , \u5206\u9694
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

