
server:
  port: 8203
spring:
  application:
    name: zipkin-client-b
  zipkin:
    base-url: http://ZIPKIN-SERVER
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
