server:
  port: 8201
spring:
  application:
    name: zipkin-server
  main:
    allow-bean-definition-overriding: true
management:
  metrics:
    web:
      server:
        auto-time-requests: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
