
#为ribbon-customer指定服务端口
server:
  port: 8764
spring:
  application:
    name: cosumer-ribbon #指定应用名
#指定eureka注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/