server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shf-1218/springcloud-config-repo.git
          search-paths: springcloud-config-repo
          username:
          password:
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
